### ISSUE TITLE
multicomponent AVA

### ISSUE THREAD

**Issue by liuyoufang** [PyLops/pylops#173]
I am looking into the possibility of using pylops for simultaneous inversion using PP and PS inversion. Although the model parameters are the same between PP and PP+PS joint inversion, the G matrix and the data size would be different when adding the PS data into the inversion. I have not figure out a way to update the G matrix correctly based on the joint inversion scheme. Maybe this issue would help me to sort things out.

**Comment by cako** [comment]
Hi @liuyoufang could you share some code of what you have tried? This would make it easier to help. From the top of my head I would suggest vertically stacking the PP/PS operators and data using the VStack linear operator. This would ensure that they are inverted jointly. You can add a relative importance to one of the components by multiplying the equations of one of the components with a percentage. The system would look something like this:

```
[   dPP ] = [ GPP ] m
[ μ dPS ]   [ GPS ]
```

**Comment by mrava87** [comment]
Hi @liuyoufang,
I wanted to follow up on this. Based on our email discussions I went ahead and modified some of our avo routines to make them more easily extendible to other avo modeling equations and to joint inversion. What happens under the hood in PrestackInversion is exactly what @cako says.

An example of how to do PP-PS inversion is here: https://pylops.readthedocs.io/en/latest/tutorials/prestack.html#sphx-glr-tutorials-prestack-py

It should be easy now for you to include your other avo models in the avo file and add flags for the in the prestack file. We will be happy to have more so when you have time consider adding yours as we discussed some time ago :)

**Comment by liuyoufang** [comment]
Hi Dr. Ravasi,

So sorry for this late reply. I recently had some important personal things
to take care of (like having the first child).

I am writing this email to see how I should properly cite the Pylops in the
manuscript that I am working on at the moment. Basically, I tried the
Curvelet wrapper in Pylops on processing some fiber optics data.
Please let me know what you think about it.

Congrats on your new position and adventure in KAUST.

Cheers,
Youfang

**Comment by mrava87** [comment]
Hi Youfang,
Congratulations :)

Nice to hear you are using pylops with DAS data. Sure it would be great if you can cite our main paper (reference in the Pylops repo README file) and of course also cite the papers Curvelab is based upon :)

PS: some time ago I decided to push what we had so far with PS data - here is an example https://pylops.readthedocs.io/en/latest/tutorials/prestack.html#sphx-glr-tutorials-prestack-py - as well as making the interface a bit more general so that one could write their own AVO coefficients and pass them (so not to be limited to what pylops has built-in)… not sure if you still work on this but I thought you may be interested to know ;)
