### ISSUE TITLE
R-linear operators

### ISSUE THREAD

**Issue by ar4** [PyLops/pylops#230]
Some operators are only R-linear, such as Re, Im, complex conjugation, and RFFT. Is there an interest in including these in PyLops? If so, I think the dot product test would need to change to include a special case for these operators, where the inner product is performed with complex values converted to R^2: <a+ib, c+id> = ac + bd.

I can create a pull request with this if desired.

**Comment by mrava87** [comment]
Hi @ar4,
thanks for the suggestion. Indeed we have some of such operators but I never personally thought about this too much other than knowing that these operators aren't fully linear as you say. For example in `test_ffts` we currently have:

```
# FFT with real=True cannot pass dot-test neither be inverted correctly,
# see FFT documentation for a detailed explanation. We thus test FFT.H*FFT
if par['real']:
    FFTop = FFTop.H * FFTop
    assert dottest(FFTop, par['nt'], par['nt'],
                   complexflag=0, tol=10**(-decimal), verb=True)
```

I am definitely up for making some changes in the dot test to handle these cases more consistently. Please go ahead and make a PR. The only thing I am a bit unsure is how we tell an operator is R-linear. The best would probably be to have an extra flag for every operator like the `explicit` we have now, but perhaps to start we can just have a flag for the dottest routine if you don't want to go through each operator and add the flag ;) Or perhaps you have a better idea?

**Comment by ar4** [comment]
The two options that I can think of are a flag, as you suggest (perhaps it could default to C-linear, so we don't need to add it to everything), or a new class RLinearOperator that inherits from LinearOperator. The latter would act like a flag - the dottest would check the class and if it is an RLinearOperator it would apply the R-linear version of the test. Do you have a feeling for which would be most Pythonic? I imagine that the composition of an R-linear operator with another operator (R-linear or C-linear) will be an R-linear operator, so it would be a nice touch if the R-linear property spread that way. Do you think the most elegant way to do that would be to add something to matmat to check if one of the operators is R-linear, and, if so, make the output R-linear?

I haven't checked the PyLops version, but RFFT implementations are usually not perfectly R-linear (it might work if you only use real numbers, as in your example, but not work for the full R-linear test). It is possible to create an operator that is. I can add it. The output is a little different, and the modification depends on the dimensionality (I don't know if there is a method of making the modification that generalises to any dimension - I do it as a special case for each dimension), so what do you think of creating new operators RFFT, RFFT2, and RFFT3?

**Comment by mrava87** [comment]
Thanks :)

I am not sure either which option is more pythonic. I like the idea of a `RLinearOperator` class as this should be less invasive on old operators. We could for example just change:

```
class _RealImagLinearOperator(LinearOperator):
``` 
into 
```
class _RealImagLinearOperator(RLinearOperator):
```
and same for ``_ConjLinearOperator`` and then use `isinstance` in the dottest to check how to perform the test.

I suspect `RLinearOperator` will be just identical to `LinearOperator` to begin with but this way some methods may be modified more easily then if we do use the flag. And yes, I think it makes sense if we go through the effort of having RLinearOperator to automatically infer when we sum/multiply/stack operators if the resulting one if CLinear or RLinear. I think without making big changes the best would be in the `dot` method when _ProductLinearOperator is invoked to check if either of the operators is RLinear and wrap the output into a RLinearOperator similar to what we have in the `aslinearoperator` function. At least this is the first thing that comes to my mind, maybe its possible to be more elegant. On the other hand I would think that we may need to do also changes to operators like HStack, VStack, BlockDiag because I guess if one operator is RLinear the entire combined operator should be right?

RFFT: so far we use `np.fft.rfft` and `np.fft.irfft` for the numpy backend when the user sets the real flag to True. For Pyfftw we just make sure the size of the array is half+1 and that the type of the input signal is float and FFTW does know how to handle. I am not sure I know what exactly you mean when you say that RFFT are not perfectly R-linear, it would be good if you can check and if PyLops one is not and know how to make it that would be very nice :) I would think making RFFT, RFFT2 and RFFT3 is a good idea and we can always readapt a bit FFT, FFT2 such that under the hood it calls the RFFTs when real=True so users don't need to make changes to their code but they will get the more correct RFFT (assuming nothing dramatic changes in codes using FFT with real=True - we have some examples we can try also in the tutorial and check before going for the switch)
