### ISSUE TITLE
Fix all return statements without if else

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops#26]
Modify all return statement patterns:
```
if: 
    return ... 
else: 
   return ...
``` 

to always return once (and the same number of elements - *this change can only be implemented in v2.0.0*)

**Comment by marcusvaltonen** [comment]
There is an old paradigm saying that a single return statement is a good practice. This can be traced back to "Single Entry, Single Exit" design patterns when FORTAN and assembly programming were prevalent [1]. Lots of things has happened since, and I think that in many cases (but not all) code-readability is better with multiple statements (which is really what it comes down to in the end).

Take e.g. your code snippet above. Which one is easier to read?
```
if <condition>:
    return a
return b
```
where I took the liberty to enforce pylint practice "no-else-return" (R1705) [2]. Compared to
```
if <condition>:
    tmp = a
else:
    tmp = b
return tmp
```
Of course these are small examples, so let's look at something a bit more complex:
```
def  calculate_union(a: Optional[List[int]], b: Optional[List[int]]) -> List[int]:
"""Returns the union of elements in a and b."""
tmp = None
# Handle cases when a or b in None
if a:
    if b:
        # TODO: a and b are not None or empty. Compute the union.
    else:
        tmp = a
else:
    tmp = b
return tmp
```
Or my preference:
```
def  calculate_union(a: Optional[List[int]], b: Optional[List[int]]) -> Optional[List[int]]:
"""Returns the union of elements in a and b."""
tmp = None
# Handle cases when a or b in None
if not a:
    return b
if not b:
    return a
# TODO: a and b are not None or empty. Compute the union.
return ...
```
I just want to nuance the discussion. I strongly agree with the McConnel's "Code Complete: A Practical Handbook of Software Construction, Second Edition" (section 17.1, online resource: [3]) that says:
(1) Minimize the number of returns in each routine (NOTE: not prohibit multiple returns, but minimize the amount)
(2) Use a return when it enhances readability

### Resources
[1] https://softwareengineering.stackexchange.com/questions/118703/where-did-the-notion-of-one-return-only-come-from
[2] https://pylint.pycqa.org/en/latest/messages/refactor/no-else-return.html
[3] https://flylib.com/books/en/2.823.1.141/1/

**Comment by cako** [comment]
I agree with this. I think a single point of exit is not conducive to good code quality or readability on its own. I would suggest we close this issue as wontfix.

**Comment by mrava87** [comment]
Sounds good! This was triggered by a colleague which claimed multiple returns are bad. Bad as you say, there is no golden rule or total agreement on this, so I’m happy for this to be closed and we just need to strike the right balance.

Btw, there are a few places where however we should consider changing the output of an if else statement with return, as so far the

**Comment by cako** [comment]
That sounds good!

**Comment by marcusvaltonen** [comment]
Sounds good!
