### ISSUE TITLE
NMO operator

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops#29]
Create ``NMO`` operator performing NMO modelling like in http://sepwww.stanford.edu/sep/prof/bei/vela/paper_html/node6.html

**Comment by cako** [comment]
I was working on a couple of methods for this and ran into some problems with the `Spread` operator. Would you mind taking a look a this notebook: [NMO_tests](https://gist.github.com/cako/5ce4d1c3c98c9009683be250663afb5c)? The problematic part is the use of the `Spread` operator with a function at the very end of the notebook.

**Comment by mrava87** [comment]
Sure :) I am not sure the Spread operator can be used for this because NMO is not a domain-to-domain operator but more an interpolator moving things around in the same domain (I remember thinking about this in the past but never really trying so perhaps I’m wrong, let’s me check your notebook first)

**Comment by mrava87** [comment]
Let me try to explain this with your example. 

If I take your Spread where you created the table yourself and look at `table[10, 200]` this will have lots of zeros and only one non-zero value. This means that for every spread operator it will try to put the values at all x locations and for those where the return value is 0 at time 0. (whilst for one single x sample at the correct time). Whilst Spread was initially thought to be a one-to-many type of operator, take value at x0-t0 in m and put it along x-t in data. I think for one-to-one operators, from x0-t0 to x-t0 like NMO, which is what I would call a push operator, we should make an operator that is more efficient because it does this task alone. But, you can actually use Spread by blanking out those x locations where you don't want anything to happen by putting `np.nan` in your table.

```
def create_tables(taxis, haxis, vel_t):
    table = np.full((par["nx"], par["nt"], par["nx"]), np.nan)
    dtable = None
    dt = taxis[1] - taxis[0]
    ot = taxis[0]
    nt = len(taxis)
    for ix, off in enumerate(haxis):
        for it0, (t0, vrms) in enumerate(zip(taxis, vel_t)):
            tx = np.sqrt(t0 ** 2 + (off / vrms) ** 2)
            it0_frac = (tx - ot) / dt
            itx = floor(it0_frac)
            w = it0_frac - itx
            if 0 <= itx and itx + 1 < nt:
                table[ix, it0, ix] = itx
    return table, dtable
```
(ignoring dtable for now)

Whilst for the on-the-fly this works. You were passing the wrong outputs, you actually should simply return an array of t times where the x axis is implicitly assumed to be the entire axis. Again we can trick the operator using nans

```
def fh(ix0, it0):
    tx = np.full(par['nx'], np.nan)
    tx[ix0] = np.sqrt(t[it0] ** 2 + (x[ix0] / vel_t[it0]) ** 2)
    it0_frac = (tx - par["ot"]) / par["dt"]
    itx = np.floor(it0_frac)
    if itx[ix0] > par['nt']-1:
        itx[ix0] = np.nan
    it0_frac = None
    return itx

SpreadNMOfun = Spread(d.shape, d.shape, fh=fh, interp=False).H
```

See here for an example of a function like fh https://github.com/PyLops/pylops/blob/82cb9a5b858ffa1414cee374cc4960eae0291b6f/pylops/signalprocessing/Radon2D.py#L249

**Comment by cako** [comment]
Thanks, this makes a lot more sense. By creating a vector with all NaNs instead of zeros, the running time halved, since it does not need to add all these zeros anymore.

Your function code also works, so that's great. I guess what I was not understanding were the inputs/outputs of the function. From your example then that would be something like this?
```python
def f(ix0: int, it0: int) -> np.ndarray((nx,)):
    ...
```
Because you are mapping from (x0, t0) space to (x, t(x)) space. The index in the output vector then represents the underlying x-space, and its value is the (index of) the value in t-space. Does that sound right?

Just out of curiosity, how would one implement the weights, in terms of function signature? For example, this doesn't work:
```python
def fh(ix0, it0):
    tx = np.full(par['nx'], np.nan)
    tx[ix0] = np.sqrt(t[it0] ** 2 + (x[ix0] / vel_t[it0]) ** 2)
    it0_frac = (tx - par["ot"]) / par["dt"]
    itx = np.floor(it0_frac)
    if itx[ix0] > par['nt']-1:
        itx[ix0] = np.nan
    it0_frac = None
    w = np.ones_like(itx) # Dummy weight
    return itx, w # Added as second output

SpreadNMOfun = Spread(d.shape, d.shape, fh=fh, interp=True).H # Enabled interp

```

By the way, I updated the gist ([NMO_tests](https://gist.github.com/cako/5ce4d1c3c98c9009683be250663afb5c) with your examples. I also added some code for the adjoint and inverse of the Reversible NMO operator. I think at some point I'd like to write a tutorial on NMO based on these examples. My idea was to do a comprehensive how-to on implementing an operator from scratch vs. leveraging current operators (like FFT and Spread) to build new operators.

**Comment by mrava87** [comment]
That’s correct. You can either have one output (the case you refer to) or two (including the decimal correction for linear interpolation behavior). What error do you get?

This behavior was specifically thought for real spreading where you know that for any x0,t0 in the input you want the value to be spread over x,t(x). The use of nans is to handle the case that t(x) is larger than the maximum allowed t. Turned out to be useful to handle cases like the NMO operator that is more like a data rearrangement than a spread ;)

Good idea regarding the tutorial, it is a nice example of using previously made operators for a different task :)

**Comment by cako** [comment]
Awesome, I got it working now. The problem was the indexing. When using `fh` with two outputs, `self.interp  = True` [gets set automatically (ignoring user input)](https://github.com/PyLops/pylops/blob/master/pylops/basicoperators/Spread.py#L163-L168). This in turn requires the [array to be indexed at `indices + 1`](https://github.com/PyLops/pylops/blob/master/pylops/basicoperators/Spread.py#L194), which will be out of bounds if the function returns indices between 0 and n-1 (which is the standard when *not* using interpolation).

So the fix is to protect those indices:
```python
    ...
    if itx[ix0] < 0 or itx[ix0] + 1 >= nt:
        itx[ix0] = np.nan
    w = np.ones_like(itx) # Dummy weight
    return itx, w # Added as second output
```

At some point I will try to document this a bit better on the `Spread` documentation. Thanks for the help!

**Comment by mrava87** [comment]
Great! I should have done that myself before ;) in the past when making Spread I had immediately used for Radon so I thought an example would make it clear how to use it but I realize that example isn’t that simple either so better to document that explicitly :)
