### ISSUE TITLE
Alter development flow

### ISSUE THREAD

**Issue by cako** [PyLops/pylops#306]
## Motivation
The current development flow is to develop entirely on the `master` branch, with stable versions being tagged as releases. On ReadTheDocs, the latest documentation always refers to the latest `master` commit. As breaking changes are introduced when developing the next version, the documentation can rapidly change, break and generally become confusing for users. In addition, this causes an issue when introducing bugfixes: since the development version will have many other changes that are not just bugfixes, it is hard to release minor versions that simple patch existing versions. Currently one would have to branch from the release version, import the commit as a cherry pick, and then tag that branch as the new release. Merge conflicts are usually harder to solve in these cases.

## Proposal
I propose a few changes to the process. First, we move the development to a `dev` branch, which can potentially even be broken as we develop the library. Second, we maintain master as the latest stable, which should essentially be equivalent to the last released version. This will allow us to quickly introduce bugfixes to the latest stable without having to worry about all the other changes in `dev`.  In addition, new users cloning the master branch won't have to deal with rapidly changing code. Finally, to make the documentation compatible with this change, we should change the [latest docs](https://pylops.readthedocs.io/en/latest/) to reflect the `dev` branch, [stable](https://pylops.readthedocs.io/en/stable/) to `master` and set stable as the default landing page for documentation.

## Migration
Currently, `master` introduces several breaking changes compared to the latest release (v1.16.0), but is still very far from v2.0.0. With that said, the breaking changes are not enormous and mostly related to bugfixes/some new features. I think we can release v1.17.0 with the current master (maybe with some cleanup on documentation to ensure that changes are documented), tag it as v1.17.0 and move development to `dev`. From then on, we can focus on delivering v2.0.0.

**Comment by mrava87** [comment]
Alright, let me highlight a few points and we can come up with a final plan after that:

1. Readthedocs: fair point, I agree it is a good idea for people to land on a 'stable' documentation, which we likely would like to the latest release (see second screenshot, Stable points to that by default). I am attaching a screenshot of Readthedocs settings, this could be very easily fixed by changing the first dropdown to Stable instead of Latest. This would not need any Github related changes. If you agree I can make this change instantly?

<img width="815" alt="Screen Shot 2022-01-25 at 12 39 48 PM" src="https://user-images.githubusercontent.com/22675848/150951473-81847079-0e5a-45f0-9d0e-c003876984c7.png">
<img width="919" alt="Screen Shot 2022-01-25 at 12 43 26 PM" src="https://user-images.githubusercontent.com/22675848/150952100-b10afeb3-f297-4131-9a7d-5674d209488d.png">

2. Dev branch: even though the above can be implemented independently, I see why we want to have a new `dev` branch and I like the idea of having a fast track to fixing bugs (in master) and a branch we work on and merge just before we want to do a release. Doc-wise, we can make Readthedocs point to stable as entry point and dev as latest. I currently don't see a way to have readthedocs showing both dev->latest, last release->stable, and master. I don't seem to see a way to add new tags, which means this way we would need to leave master behind - but that may be okish as it's never meant to be different from the last release?
 
3. `Currently, master introduces several breaking changes`: this is the only thing I disagree. We should never introduce breaking changes, the exception being bug fixes (I am sure everyone is happy for any bug to be fixed as soon as it is spotted) or very minimal changes that would not majorly impact a user that has a working code (which should be agreed between the main devs like we did recently for the slope estimator) - otherwise we would lose trust. Btw, a new feature is not a breaking change as long as the old behavior is maintained (say we add a new feature and keep it as `False` as default). If we really want to make major breaking changes we need to move to v2.0.0, which is eventually going to happen at some point as soon as we have time to work on it :)

**Comment by mrava87** [comment]
So let me summarize, shall we do the following:

- Create a dev branch in `https://github.com/PyLops/pylops`.
- Always make PRs onto `dev` (unless is a bug fix, then to `master`)
- Merge `dev` into `master` any time we want to make a new release (and handle all conflicts, hopefully few ;) )
- Move rtd default version to stable and default branch to dev

Anything else?

**Comment by cako** [comment]
Yup, that sounds like a good idea. On your point 3, you are right, they are not breaking changes per se, more like new features.

I have gone ahead and merged #307 (all tests were passing) and created a dev branch as well. Next steps are to release version 1.17.0 with the current master and do the changes on RtD.

**Comment by cako** [comment]
By the way, a good read regarding this is the "Git flow": https://nvie.com/posts/a-successful-git-branching-model/

**Comment by mrava87** [comment]
Great! I’ll finalize the release at the weekend.

And make all changes including the GitHub action one so next time we can deploy to PyPI automatically :)

**Comment by mrava87** [comment]
Rtd is configured as agreed now.  All is left to do is to work on `dev` after the next release. I think as part of the release process I am also going to add something about this in the contributing page so it appears in the stable version of the site already :)

**Comment by cako** [comment]
One last thing before we close this issue, should we change the "Default branch" from master to dev? This will ensure that "all pull requests and code commits are automatically" submitted to dev, and will prevent us from releasing new versions "accidentally".

**Comment by mrava87** [comment]
Yes definitely. I was already close to forget once ;)

**Comment by mrava87** [comment]
Basically now you cannot simply from dev click `Contribute` and make a PR. You need to do it from master and then when you are to make the PR switch master with dev so dev goes into master... I guess this is fine? And it saves us from remembering every time to change to dev when we do a PR from our forks :)

**Comment by cako** [comment]
Yes, I think that's a fair solution. Closing this issue!
