### ISSUE TITLE
Bug in Sliding2D

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops#311]
This piece of code used to work in previous versions (going to check up to which one...):

```
par = {'ox':-140, 'dx':2, 'nx':140,
       'ot':0, 'dt':0.004, 'nt':200,
       'f0': 20}

v = 1500
t0 = [0.2, 0.4, 0.5]
px = [0, 0, 0]
pxx = [1e-5, 5e-6, 1e-20]
amp = [1., -2, 0.5]

# Create axis
t, t2, x, y = pylops.utils.seismicevents.makeaxis(par)

# Create wavelet
wav = pylops.utils.wavelets.ricker(t[:41], f0=par['f0'])[0]

# Generate model
_, data = pylops.utils.seismicevents.parabolic2d(x, t, t0, px,
                                                 pxx, amp, wav)
data = data[:, 60:]
pad = 12
data = np.pad(data, ((pad, pad), (pad, pad)), mode='edge')

dimsd = data.shape
nwin = 26
nover = 4
dims = (7*256, 256)

Op = FFT2D((nwin, dimsd[1]), nffts=(256, 256))
Sop = Sliding2D(Op.H, dims, dimsd, nwin, nover,
                tapertype=None, design=True)
Sop1 = Sliding2D(Op.H, dims, dimsd, nwin, nover,
                 tapertype='cosine', design=True)

y = data.copy()
x = Sop.H * y.ravel()
x = x.reshape(dims)
y1 = Sop1 * x.ravel()
y1 = y1.reshape(dimsd)

xinv = Sop1.div(y.ravel(), 50)

yinv = Sop1 * xinv.ravel()
yinv = yinv.reshape(dimsd)

dottest(Sop, Sop.shape[0],  Sop.shape[1], complexflag=2, tol=1e-2)
```

As `Sliding2D` has not changed in a while I suspect this may be to the changes in ``FFT2D``

**Comment by cako** [comment]
I haven't figured out what's the best way possible to fix, but I just wanted to let you know where I believe the issue is coming from. Somewhere along the way, some complex values are being lost. By altering these three lines, I was able to get the example to work.

https://github.com/PyLops/pylops/blob/8b03613118b0cd87226b111b3fcf540982671494/pylops/basicoperators/HStack.py#L132

https://github.com/PyLops/pylops/blob/8b03613118b0cd87226b111b3fcf540982671494/pylops/basicoperators/HStack.py#L137

https://github.com/PyLops/pylops/blob/8b03613118b0cd87226b111b3fcf540982671494/pylops/basicoperators/Restriction.py#L140


Edits (sorry for picture)

![image](https://user-images.githubusercontent.com/645570/151450042-3829b2c7-d89a-42b6-bd6c-d9f045b3075b.png)

**Comment by cako** [comment]
Ignore the comment above. The problem was the `Restriction` within the sliding operators was not inheriting the correct dtype. I think at some point we need to rethink the dtypes!

**Comment by mrava87** [comment]
Thanks! I got this error running some old code and did not have time do figure it out immediately, I was planning to look at it today. Thanks for doing it already. 

I suspected it must have been something to do with FFT as we haven’t changed neither Sliding2D nor Restriction lately. Let me check the PR.

I would have been more worried about the first changes as it seems you had to force a complex type which of course we can’t do as default.

But yes, it is really mostly FFT’s fault that dtypes sometimes play funny but we should find a way to streamline this as much as possible. Or at least make sure all composite operators inherit

**Comment by mrava87** [comment]
Indeed, I tried running the code with `v<1.14.0` and the dottest works giving warning on HStack about casting complex. It breaks exactly at `v1.14.0` which is when `Fixed pylops.utils.dottest.dottest for imaginary vectors and to ensure u and v vectors are of same dtype of the operator` was introduced :)
`

**Comment by mrava87** [comment]
As I was not ready to make the new release yet (hopefully I get some time tomorrow), I merge this into the main... we want this bug to get into the release :)

**Comment by cako** [comment]
Agreed! Glad you found the source of the change. Now I can rest easy that I didn't mess up the FFTs :P
