### ISSUE TITLE
V2.0 and FirstDerivative

### ISSUE THREAD

**Issue by matthewamarcus** [PyLops/pylops#387]
The docs for Pylops refer to V2.0, which doesn't seem to exist.  In particular, operators like FirstDerivative have an axis= keyword which does not exist in V1.18.2, the latest I can find.  This is important because I'm working on a tomo reconstruction which will need a regularizer |delQ|^2 where Q is Q[iq,voxel] and the derivatives should only be done on the voxel indices, not iq (Q is a multicomponent object),.  I tried a simple test of making a 2D matrix and calling Dop = pylops.FirstDerivative((ny,nx)) with ny,nx being the dimensions and it bombs.  Copying the source of the new FirstDerivative operator from the docs doesn't work as it depends on stuff that isn't in V1.18.2.

**Comment by cako** [comment]
Hi @matthewamarcus, thanks for the heads up. We have v2.0 in the pipeline but it's not out yet. The docs badge was linking to the latest (dev) instead of stable. That should be fixed by #388. Find the stable docs here: https://pylops.readthedocs.io

The reason your code isn't working is because you were using v2.0 syntax (which again, hasn't been released). In v1.18, it should be is called like this:
```python
import numpy as np
from pylops import FirstDerivative
ny, nx = (101, 201)
x = np.ones((ny, nx))
Dop = FirstDerivative(ny * nx, dims=(ny, nx), dir=0)
y = (Dop @ x.ravel()).reshape(x.shape)
print(np.allclose(y, np.zeros_like(y)))
```
if you want the first derivative to be on the first dimension, that is, y. If you want on both, you should do something like this:
```python
Dopy = FirstDerivative(ny * nx, dims=(ny, nx), dir=0)
Dopx = FirstDerivative(ny * nx, dims=(ny, nx), dir=1)
Dop = Dopy @ Dopx
```
You can find this syntax in the online docs, but also if you type `?pylops.FirstDerivative` on an interactive Python shell (ipython).

As you can see it is a little verbose. That's one of the reasons we revamped many of the operators, including `FirstDerivative`.
