### ISSUE TITLE
pylops.Restriction in v1.18.1

### ISSUE THREAD

**Issue by PAULGOYES** [PyLops/pylops#389]
I am using the Restriction as: 
Rop = pylops.Restriction(par['nt'] * par['nx'], iava, dims=(par['nx'], par['nt']), dir=0, dtype=np.float64)
but I am getting the next error:
TypeError: __init__() got multiple values for argument 'dims'

It is possible an error with the lasted version ?. How can I install an old version using
 !pip install git+https://github.com/PyLops/pylops.git

Here is the example in google-colab with the error:
https://colab.research.google.com/drive/1ws_ies6spyGyqWgQTi7EpLnfk8Zik3AK?usp=sharing

**Comment by PAULGOYES** [comment]
with v1.17.0 it works fine for me (**pylops.Restriction**). 
I have installed it using: !pip install  git+https://github.com/PyLops/pylops.git@v1.17.0

**Comment by cako** [comment]
Glad you got it working. The root of the issue is the fact that installing from git does not give you the latest stable version, but actually clones the latest development version. In the dev version, many operators will not require the `nx * nt` argument in the beginning, so it thinks you are supplying dims twice, once as a positional argument (`nx * nt`) and once as a keyword argument (`dims=(nx, nt)`). We do have a migration document, but of course you couldn't have known you were actually on the dev version. I should probably put this in the FAQs 😅

For future reference, I recommend always installing from pip or conda. I know colab doesn't have conda, but you can install it with pip as a package and not a repo: `!pip install --upgrade pylops`. I tested this version and it works. It is also the latest stable so I would recommend using that one.

@mrava87 I think Paul's issue raises a deeper problem which is that cloning apparently gets from dev. This is because we made it the "main" branch in the GitHub settings (on my request!). However, I didn't realize this also changed the cloning branch. Do you think we should switch it back? Another problem is the versioning on the dev branch. Paul (very reasoably) assumed the bug was in 1.8.1 because the dev version has this version number: `1.18.1.dev141+g9f6ee42`. Could we see about getting this updated to maybe `2.0.0.dev` or something?

**Comment by mrava87** [comment]
Mmh I am not sure this is a real problem. If people want to pip install from GitHub or clone they should know how to do it. Users should use pip or conda, devs can do more advanced things but we should assume they are more experienced and know how to do it.

For example, to pip install a specific branch from GitHub you need to add @branchname at the end… we say this in the documentation :)

For cloning is even easier as GitHub gives you the command based on the branch you are in.

I guess we could switch back having master as the main branch, I don’t have strong opinion about that. 

Regarding versioning, we use an automated tool for it, I would NOT mess up with it and what Paul get is actually correct… the tool knows where are at v1.8.2 and does the versioning from there :)

**Comment by mrava87** [comment]
PS: our latest version is 1.18.2, not sure why he sees 1.18.1blabla… let me check.

**Comment by cako** [comment]
Ok, no problem. I might add the github thing to the FAQ at some point

**Comment by mrava87** [comment]
Yes, that would be helpful :)

**Comment by mrava87** [comment]
And btw, I have retroactively re-added the `v1.18.1` tag, so that the version number in development phase is `1.18.2.dev5+ge267da9`. Anyways, once we are done with v2 everything will go back to normal :)

**Comment by cako** [comment]
Great, thanks!
