### ISSUE TITLE
TV Regularization example is not working

### ISSUE THREAD

**Issue by fabiojdf** [PyLops/pylops#397]
I'm trying to run the TV Regularization example (https://pylops.readthedocs.io/en/latest/gallery/plot_tvreg.html#sphx-glr-gallery-plot-tvreg-py) and i'm facing bugs in a lot of routines.

versions:
`python==3.9.7`
`pylops==1.18.2`

Actually, seems like some functions/classes such as `pylops.optimization.leastsquares.regularized_inversion` and `pylops.optimization.sparsity.splitbregman` has changed its name.

There is an older pylops release that this example works?

**Comment by mrava87** [comment]
Hi @fabiojdf,
currently we are making several changes to pylops and we will soon release a v2 version. Among those changes is the renaming of solvers because we are creating both class based and function based versions. But this is currently only in the dev branch and DOES not affect the current releases.

Are you sure you are using v1.18.2 as this should still work with the original solvers. Can you please print pylops.__version__ and the error you get

**Comment by fabiojdf** [comment]
Hi @mrava87 !

I thank you for your answers. I was able to run it from the documentation of the stable version. Everything is running correctly here.

The work you have been doing at PyLops is awesome!
