### ISSUE TITLE
Use ruff instead of flake8 for linting

### ISSUE THREAD

**Issue by rohanbabbar04** [PyLops/pylops#485]
Use [ruff](https://github.com/charliermarsh/ruff) instead of flake8
 - It's faster than flake8
 - Linting is better with ruff

**Comment by mrava87** [comment]
Hello,
I am not sure about changing something we used for long time and are satisfied with. @cako is currently away, once he is back at work he can give us his opinion as he introduced flake8 support to pylops.

**Comment by cako** [comment]
I think ruff has a lot of potential, but I am hesitant port over to it right now for two reasons:

1. Ruff does not support [pattern matching](https://github.com/charliermarsh/ruff/issues/282). The fix for this should be coming soon.
2. [Ruff does not flag errors which are fixed by black.](https://github.com/charliermarsh/ruff/issues/1076#issuecomment-1338218786) I understand we are using black as a pre-commit hook, but pre-commit hooks are not mandatory and can be bypassed. I would hate to be missing linting suggestions because someone at some point did not use black.

For those reasons I would rather wait until ruff becomes more mature before moving the whole project over to it. I am closing this issue as wontfix for now.

**Comment by cako** [comment]
@mrava87 Ruff has made a lot of progress in this year. I've been using it almost exclusively for new projects. It's crazy fast! I think once they close these issues, we should think about migrating to is:

https://github.com/astral-sh/ruff/issues/2402

https://github.com/astral-sh/ruff/issues/5188

**Comment by mrava87** [comment]
Sounds like a good plan! I haven't followed much but I trust you, just shout when you think is time :)
