### ISSUE TITLE
Incorrect reshaping if operators maps 1D to ND.

### ISSUE THREAD

**Issue by RendersJens** [PyLops/pylops#500]
Since updating to Pylops 2.0, some operators started returning nd arrays instead of raveled or 1d arrays. At first I thought this was intended, so I just kept using 1.18, but I now managed to pinpoint a situation where this happens and it is clearly not intended.

Code to reproduce:
```python
import pylops
import numpy as np

image = np.zeros((5, 5))

S = pylops.Identity(image.size)
F = pylops.signalprocessing.FFT2D(image.shape)

v = image.ravel()

# these are unexpected, they print (5, 5) but should be (25,)
print((F @ S @ v).shape)
print((F.T @ S @ v).shape)

# these all work as expected, they all print (25, )
print((F @ v).shape)
print((F.T @ v).shape)
print((S @ S @ v).shape)
print((S @ F @ v).shape)
print((F @ F @ v).shape)
print((F.T @ F @ v).shape)
print((F @ F.T @ v).shape)
print((F.T @ F.T @ v).shape)


# the problem can be avoided using parethesis, because this avoids the product operator
print((F @ (S @ v)).shape)
print((F.T @ (S @ v)).shape)
```

So the only situation in which I can reproduce it is when an FFT2D (or FFTND) appears as the left factor of a product operator, but not if the right factor is also an FFT. I will try to dig some more, but any insights are already appreciated.

I currently use Pylops 2.1.0, and this situation first appeared in 2.0. It was not present in 1.18.3.

**Comment by RendersJens** [comment]
I have digged further.

The ouput is correctly raveled by .matvec() and .rmatvec(), but it is reshaped back to (5, 5) in the .dot() function:
https://github.com/PyLops/pylops/blob/dev/pylops/linearoperator.py#L616

This happens if `is_dims_shaped` is true, which is `is_dims_shaped = x.shape == self.dims`, but then it gets reshaped to the shape self.dimsd (not self.dims).

- In the case of the FFT2D operator, self.dims = (5, 5) so `is_dims_shaped` is false, so the output is not reshaped and keeps shape (25,)
- In the case of the Identity operator self.dims = (25,) so `is_dims_shaped` is true, so the output is reshaped to self.dimsd which is also (25,)

Now where it goes wrong:
For the product operator P = F @ S, we get P.dims = (25,) so `is_dims_shaped` is true, but P.dimsd = (5, 5). Therefore the output now gets reshaped to (5, 5), which is unexpected.

**Comment by RendersJens** [comment]
Based on the above, here is a much simpler example:

```python
import pylops
import numpy as np

S = pylops.Sum((5, 5), axis=0)
v = np.zeros(5)

print(S.T @ v) #(5, 5) array, should be (25,)
```

Sum maps ND arrays to one dimension lower, so 2D to 1D. The transpose of sum is then an operator that maps 1D to higher dimensions, so it has this bug too.

**Comment by cako** [comment]
Hi @RendersJens,

So, before I explain what is going on, let me first point you towards this [Migration from v1 to v2 document](https://github.com/PyLops/pylops/blob/dev/MIGRATION_V1_V2.md#operator-interface) that explains how you can disable ndarray multiplication. TLDR: call `pylops.set_ndarray_multiplication(False)` at the beginning of your script. Try this with v2.1 and it should work.

Onto the problem at hand. As you noticed, all operators in v2 have `dims` and `dimsd`, which describe how outputs will be shaped after multiplication. The behavior of reshaping is defined by the "input" vector. If it is shaped like `dims`, the output will be reshaped to `dimsd`. If it is flattened, the output will also be flattened. To figure out which one you will get, [check this table](https://github.com/PyLops/pylops/blob/dev/MIGRATION_V1_V2.md#table-of-supported-multiplication-shapes).

With that in mind, let's look at your last example:

```python
S = pylops.Sum((5, 5), axis=0)
v = np.zeros(5)
print(S.dims) # (5, 5)
print(S.dimsd) # (5,)
print(S.T.dims) # (5,)
print(S.T.dimsd) # (5, 5)

# The next could be go either way, (5, 5) or (25,) since
# v.shape == S.T.dims == v.ravel().shape
# Since in v2 we prioritize ndarray notation, it will output (5, 5)
print((S.T @ v).shape) # (5, 5)
# It is useful because we can broadcast like this:
stacked_v = np.vstack((v, v, v)).T # shape (5, 3)
print((S.T @ stacked_v).shape) # (5, 5, 3)

# But we can force (25,) locally
with pylops.disabled_ndarray_multiplication():
    print((S.T @ v).shape) # (25,)
print((S.T @ v).shape) # (5, 5)

# or globally
pylops.set_ndarray_multiplication(False)
print((S.T @ v).shape) # (25,)
```

With that out of the way, let's look at your first example with the Identity. The issue there is that the Identity actually did not get upgraded to ndarray `dims`/`dimsd`. This was an oversight which generates the issues that you report. Basically since `Id.dims == Id.dimsd == (25,)`, it will always reshape the output to (25,). As you noticed, when the identity operator is multiplied, the resulting operator inherits `dimsd` from the left operator, and dims from the `right` operator. In your case, this means that `dims = (25,)` and `dimsd = (5, 5)` yielding the unexpected behavior that you reported.

To conclude, if ndarray notation breaks you code and you want to not worry about it, use the global setting to disable it. On our end, we will try to make all operators ndarray-friendly by default so that, as much as possible, things like this `F @ S @ v` outputs the same shape as `F @ (S @ v)`.

**Comment by mrava87** [comment]
PS: one thing I would like to point out is that @ does NOT call __matmat__. It calls dot that internally chooses whether to call _matvec or _matmat and this is the original behavior of scipy which we have inherited and kept.

If you look at the comments in the PR that you have pointed above you will see a very detailed description of what are now 4 possible behaviors of dot (or @ or *) that include the original two plus two new ones… in an ideal world of no bug, you are in total control to choose which behavior to use and so use pylops v1 behavior by just passing ravelled vectors to operators 😀

**Comment by RendersJens** [comment]
> For Sum, for example, this actually happens if and only if the input has 1 or 2 dimensions (beyond that pylops will already recognized when to give you a ravelled vector and when a Nd array):
> 
> I’ll add an example in a minute…
> 
> There I think the only way around is to have an extra keyword argument that a user to use to force either behavior.

Indeed this is one of the examples I showed above. And I also think the only way around is a keyword argument, which is imo much better than a global setting or context.

**Comment by cako** [comment]
> The last comment makes it sound as if it is no longer intended to make all operators work like matrices anymore, except if you use the global setting or correct context.

I personally am of this opinion and the reason why I implemented the ndarray multiplication. I find ndarray multiplication much more intuitive and user friendly, especially when using operators one is not super familiar with. It also removes reshape/ravel cruft that I felt polluted usage. But I do see the appeal of keeping everything column-vector.

I actually debated whether keyword choice was better or not, and I finally settled on a global setting. I will detail why below, but do check #348, #353 and #367 for discussion around design and implementation of this feature.
1. Keyword choices need to be set per-operator. When using many chained operators, if the user does not ensure that the keywords are consistent across all operators, one *may* get size mismatches. But they also may not, depending on how the operators are defined in the first place. I felt this would be confusing and unwieldy.
2. Another troublesome situation is code that the user does not control. Suppose within a third-party solver, an operator is created with `flatten=True`. Mixing this internal operator with a user-supplied `flatten=False` operator would likely cause the function to fail. Again, keeping track of this could become tough.
3. Reverting back to v1.x behavior would be impossible using only keywords. Each operator instantiation would need to be edited manually. Either that or the default instantiation depends on a global variable (e.g., `FLATTEN_DEFAULT = True`), but then we're back to globals.

> I fully agree with adding extra functionality to deal with nd arrays. Operators, unlike matrices, can indeed work on nd-arrays like that. But I think it is important that this is extra. Not a replacement.

I think it's just a matter of choosing the default. The pact of major version is that things can break, and we had to make an executive decision of whether to make this opt-in or opt-out. We chose to bite the bullet and make it opt-out, but I fully understand that this may not be great for some cases (and introduced some bugs!).

> Currently, you do not have all the old style matrix-like operators in your package anymore. A global setting or a context manager doesn't solve this. Now the operator works in some contexts and not in others. The action of the operators should depend, as much as possible, on their own attributes, not the context.

I'm not sure I agree with this, the global setting allows you to completely ignore ndarray multiplication in all your scripts if that is your preferred functionality. The context manager allows you to selectively ignore ndarray multiplication (I find this useful for interacting with scipy solvers). Your v1.x scripts should all work if you globally disable ndarray multiplication. We felt that this was enough of a "escape hatch" for anyone coming from v1.x.

> so that you can choose if you want to make an operator Id: R^n -> R^n or Id: R^(k x l) -> R^(k x l)

This is a very good point, and I would fully support a generic solution that works well for every operator. Unfortunately I have not been able to so far, but I am open to suggestions!

-------------------------------
I think it is very important for us as developers to try to make the usage of the library as easy as possible, since this is already quite a complicated space! If you feel like adding keyword arguments to operators will be useful, we can certainly explore that. In that case, my suggestion would be to start a Discussion with suggested use cases, expected patterns and so on. Basically anything that can help us all design and implement the feature.

**Comment by mrava87** [comment]
Thanks Carlos for adding your view on this.

Personally, I think that at times the discussion is a bit too drastic given that one can very easily choose which behavior to set as default with the global setting. However I see that this can become a sort of lazy way to hide bugs under the carpet, and I would like things to always work well without the need to resort to such a code patter.

Having said that, I want to restate what I wrote before: this is right now needed for a bunch of operators, and I believe we can easily find a way around… for most operators, as you can see by the fact that most of our examples, tutorials, and notebooks did not need change when moving from v1 to v2, if you simply pass vectors to operators you will obtain vectors - and this is what you usually want to do when interacting with solvers! So the behavior of pylops v1 is preserved and simply driven by the fact you pass a vector to operators - note that in pylops v1 if you passed a NDarray you would get an error anyways…

But, as Carlos says, there are many scenarios where you just want to quickly apply an operator that you are perhaps not very familiar at with, in this case passing an NDarray and getting an NDarray in their meaningful shape (eg for plotting) is a very good feature of pylops v2 - I think.

Going forward we could continue here or move to a discussion (I don’t have strong feelings), I see the following:

- one operator needs fixed: Identity (as discussed above… @cako are you taking care of it or shall I look into?)
- two operators need a keyword to avoid ambiguity*, which is always a bad thing (I don’t see any other way): Restriction and Sum

*ambiguity means that at some point in the chain you have a 1Darray but it isn’t clear to the operator whether you want to use NDarray (current default) or 1Darray… this should not happen

**Comment by cako** [comment]
I'm pretty much in agreement with this. I would add that there are probably other operators out there that do no have `dims` and `dimsd` set yet.
