### ISSUE TITLE
ZeroDivisionError when using forward Kirchoff operator with dynamic  = True and engine="numba"

### ISSUE THREAD

**Issue by arietu** [PyLops/pylops#527]
When I apply forward Kirchoff operator with dynamic =True and engine = "numba" an error appears at the "_matvec" method. 
![image](https://github.com/PyLops/pylops/assets/121080223/d0579f51-7f54-468a-9296-735c627191d9)

**Comment by arietu** [comment]
I forgot to mention that this happens when mode='byot' where I add my own trav and amp arrays.

**Comment by arietu** [comment]
and everything works fine when engine='numpy'

**Comment by mrava87** [comment]
Hello @arietu, this is likely due to the fact that you provide some of the amplitudes with zero. 

Without a full error report I cannot tell exactly but this is what I suspect. It may work fine with engine=numpy as numpy let’s you do a division by zero and returns inf (or nan) while numba raises an errorz

**Comment by mrava87** [comment]
Right I see. This issue was recently fixed as part of a larger PR (it is currently until review and will be merged soon :) )
